import Head from "next/head";
import Homes from "@/components/home";
import What from "@/components/What";
import { motion, useScroll, useSpring } from "framer-motion";
import Events from "@/components/Events";
import Test from "@/components/Test";
import Areas from "@/components/Areas";
import Youtube from "@/components/Youtube";
import Podcast from "@/components/Podcast";
import Footer from "@/components/Footer";
import React, { useState, useRef, useEffect } from "react";

export default function Home() {
  const [showScrollTop, setShowScrollTop] = useState(false);
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 200) {
        setShowScrollTop(true);
      } else {
        setShowScrollTop(false);
      }
    };
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
  const handleScrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  });
  return (
    <div>
      <Head>
        <title>Leadafrique International</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div className="progress-bar" style={{ scaleX }} />
      <Homes />
      <What />
      <Events />
      <Test />
      <hr className="mt-11 md:mt-32 new " />
      <Areas />
      <Youtube />
      <Podcast />
      <Footer />
      {showScrollTop && (
        <button
          className="fixed md:bottom-0 -bottom-1  md:right-3 right-5 m-5 p-3 fon-font bg-white rounded-full shadow-md text-purple-500 hover:bg-purple-500 hover:text-white transition transform duration-200 ease-in-out"
          onClick={handleScrollToTop}
        >
          Scroll to top
        </button>
      )}
    </div>
  );
}
